### ISSUE TITLE
Any chance to add a tutorial for securing entire microservice stack on Azure cloud?

### ISSUE THREAD

**Issue by meehaws** [microsoft/azure-spring-cloud-training#121]
Hi,

Great training material. 

Is there any chance to add a security layer tutorial? So that all microservices are secured in some way, not freely accesible?

**Comment by jdubois** [comment]
Security is managed at the Spring level, so it's a bit outside of the tutorial, which is focused on Spring cloud.

You'll need to use Spring Security, and there are many ways to do it:

- If you want something easy, have a look at what we do on https://www.jhipster.tech/ 
- If you're looking for something more Microsoft-centric, you can look at using AAD with Spring Security, like in this blog post: https://dev.to/azure/using-spring-security-with-azure-active-directory-mga
- I also did a quick video at SpringOne on this with my friend Josh Long: https://www.youtube.com/watch?v=UEfRGttMGRk&feature=emb_logo
