### ISSUE TITLE
Azure Spring Cloud public roadmap

### ISSUE THREAD

**Issue by hieumoscow** [microsoft/azure-spring-cloud-training#123]
Hi team, 
Thank you for the great training content.
It would be beneficial if we were to have a public roadmap for Azure Spring Cloud for easier tracking of features & bug fixes.
We do have this today with [AKS](https://github.com/Azure/AKS/projects/1) & [ARO](https://github.com/Azure/OpenShift/projects/1) roadmaps. Would be awesome to have the same setup for Azure Spring cloud too.

**Comment by jdubois** [comment]
This repository is just for the training material - the roadmap is managed by the Azure engineering team, and published by them. There are regular updates, but they won't be posted here on this GitHub repo.
