### ISSUE TITLE
UI changes to the Azure portal in "10 - Blue/Green deployment"

### ISSUE THREAD

**Issue by junnhssn** [microsoft/azure-spring-cloud-training#128]
Hello Team,

1.  In exercise 10 - Blue/Green deployment, the instruction below does not reflect the current UI of the portal.

```
Navigate to the Azure Spring Cloud instance in the Azure portal and click on "Deployments" (under Settings). You should now see the "green" deployment in the "Staging Deployment" column:
```

2.  The "deployments" blade is no longer visible under "setting" from the Azure Spring cloud instance page.

![azure-spring-cloud-overview](https://user-images.githubusercontent.com/47213023/118671037-c0e4aa00-b814-11eb-96fe-ad88a95f7d89.png)

3.  Instead, we have to navigate to the app instances under Azure spring cloud to view the deployments.

![weather-service-deployments](https://user-images.githubusercontent.com/47213023/118670937-a9a5bc80-b814-11eb-939a-6b32d351dc38.png)

4. Similarly,  the following instructions need to be updated -

```
Another solution is to use the Azure portal:

Find your Azure Spring Cloud instance
Click on the "deployment" menu
Select the weather-service application and click on Set deployment
```

Can we please update these instructions and screenshots to match the current UI? 

Thanks, and regards.

**Comment by jdubois** [comment]
Thank you, indeed the UI has changed and this needs to be updated

**Comment by junnhssn** [comment]
Hi, when can we expect these changes to be made? We have workshops scheduled for the coming week. Thanks.

**Comment by jdubois** [comment]
I have updated it in #145

**Comment by jdubois** [comment]
And thanks for notifying us @junnhssn ! Images are a pain to maintain.
