### ISSUE TITLE
Command in "01 - Create an Azure Spring Cloud instance" failing to enable the Application insights.

### ISSUE THREAD

**Issue by junnhssn** [microsoft/azure-spring-cloud-training#130]
Hi Team,

In exercise **01 - Create an Azure Spring Cloud instance** the following command : 
```az spring-cloud create \
    -g "$AZ_RESOURCE_GROUP" \
    -n "$AZ_SPRING_CLOUD_NAME" \
    --enable-java-agent \
    --sku standard
```
Fails to correctly enable Application Insights on the Azure Spring Cloud (Application Insights instance is created but Azure Spring Cloud is not enabled with it)

The only way is to manually enable Application Insights in the Portal.

![image](https://user-images.githubusercontent.com/47213023/123145709-bdc78400-d47a-11eb-80cb-ca4317375936.png)

![image](https://user-images.githubusercontent.com/47213023/123145997-0da64b00-d47b-11eb-8430-fc0d113021b8.png)

Can we please get a fix for this?

Thanks,
Junaid Hussain.

**Comment by jdubois** [comment]
Thanks for your bug report - I'm surprised by this, I remember talking with @roryp and adding this specifically as this is a new feature. Are you sure your AZ CLI is up to date? It seems to me you have an outdated version.

**Comment by junnhssn** [comment]
Hello, thanks for the prompt reply. 
Indeed we were running version 2.31.0 of Git bash. Updating it to 2.32.0 seems to have solved the above problem. Thanks.
