### ISSUE TITLE
Issue with the bash command

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/azure-spring-cloud-training#143]
Issue 1:

In [Exercise-2/ Task-4/Note after step-5](https://github.com/microsoft/azure-spring-cloud-training/tree/master/02-build-a-simple-spring-boot-microservice#create-and-deploy-the-application-on-azure-spring-cloud), provided command (az spring-cloud app create -n simple-microservice) to create the apps in Azure Spring cloud is not working need an update with __az spring-cloud app create -n <app name> -s <Azure Spring cloud name> -g <RG name> --assign-endpoint true --cpu 2 --memory 1Gi --instance-count 1_

Issue 2:

In [Exercise-5/ Task-4/ Step-1](https://github.com/microsoft/azure-spring-cloud-training/tree/master/05-build-a-spring-boot-microservice-using-spring-cloud-features#create-and-deploy-the-application-on-azure-spring-cloud),  provided command is not working. Need to replace it with _az spring-cloud app create -n <app name> -s <Azure Spring cloud name> -g <RG name> --assign-endpoint true --cpu 2 --memory 1Gi --instance-count 1___

Issue 3:

In [Exercise-6/ Task-5/ Step-1](https://github.com/microsoft/azure-spring-cloud-training/tree/master/06-build-a-reactive-spring-boot-microservice-using-cosmosdb#create-the-application-on-azure-spring-cloud), provided command is not working. Need to replace it with __az spring-cloud app create -n <app name> -s <Azure Spring cloud name> -g <RG name> --assign-endpoint true --cpu 2 --memory 1Gi --instance-count 1____

**Comment by jdubois** [comment]
Thank you @Divyasri199 

Those commands have changed recently in the cli extension, so I understand your issue. However, we don't set up the CPU or memory in the different units, so you shouldn't have been affected by those.
