### ISSUE TITLE
Issue in Exercise - 5

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/azure-spring-cloud-training#144]
In Exercise - 5> Task - 4>step - 2, I'm facing an error while running the command.

![image](https://user-images.githubusercontent.com/81952290/141107917-f5774f6a-a2f4-479a-93d8-64017a9d1bbd.png)

 The spring-cloud-microservice app's provsioning state is in `Failed` state.

![image](https://user-images.githubusercontent.com/81952290/141108183-59b3da49-fc8a-409d-b6e9-4813dc079d88.png)

I tried to use the older version of maven, git, azure CLI, curl, and zulu8. But still the issue persisted. Kindly look into this issue.

**Comment by akn9050** [comment]
Hi @jdubois , can you please help with this issue.

**Comment by jdubois** [comment]
Hi @akn9050 I'm sorry but I have several conferences talks in the next couple of weeks, so I won't be able to have a close look at this very soon.

Can you use the streaming log command using the CLI, to see what the error might be?

**Comment by Shivashant25** [comment]
Closing this issue. Using a Public GitHub repository instead of the private repository cleared the error.
