### ISSUE TITLE
How to deploy Spring Batch App to Azure and how to manage multiple instances and scheduling through config?

### ISSUE THREAD

**Issue by javaHelper** [microsoft/azure-spring-cloud-training#148]
I am new to Azure and looking to deploy several Spring Batch App to Azure. Each batch job has different scheduled say every day at 12 pm or 5pm or weekly Monday at 12 pm etc.

I would like to seek guidance on 
1) how to make the scheduling configurable for several batch apps
2) how to manage multiple instances of each batch job
3) how to make this serverless? As many batch job will run once a day and making applicable idle is really bad practice.  

Here several modules/jar file will be deployed (or sometimes one jar having multiple batch jobs in that) on Azure and using Postgres, MySQL and MongoDB for some batch jobs.

Any quick light on that?

**Comment by jdubois** [comment]
There are many ways to deploy Spring Batch to Azure, so here are just some general guidelines.
Please note that I'm closing this as this question doesn't really belong to this ticket system (this is for bugs on this specific training), but you can ping me directly or comment on this issue, and I'll do my best to answer.

- There are different ways to schedule Spring Batch jobs, but your requirements look simple enough to use a Cron configuration for this. This is doable directly inside the Spring Batch configuration. You can have a look at https://spring.io/guides/gs/scheduling-tasks/
- If you want multiple instances, you need to run your job several times. Be careful, as you can corrupt data if you are modifying the same data concurrently. This is why Spring Batch is usually configured with a database, that could lock some jobs and prevent those issues.
- You can run those jobs on Azure Spring Cloud, but indeed it might not be the best solution if your job only runs once a day. There should be options for this soon, but at the moment you would be better with another service. You can indeed use Azure Functions (which is our serverless offering), as it works with Spring: here is a sample repo https://github.com/Azure-Samples/hello-spring-function-azure that I'm also maintaining. However it's mostly for running short jobs, and you might go into timeouts, depending on what you do (but I'm guessing that if you use Spring Batch, you have some long processing to do). So instead, I would recommend having a look at Azure Container Instances, that will provide you with cheap Docker images that would be good for running Spring Batch.

**Comment by javaHelper** [comment]
Many Thanks for the detailed answer.
- Batch Jobs can be scheduled through cron jobs within its own properties file or within config repo.
- In my case running the same job multiple times will definitely corrupt the data, as data is life blood here. We're using Azure Postgresql and all metadata is managed in Postgres db, I am not finding documentation which says lock would be applied on Jobs and will make sure to be run by only 1 instance. Will need more clarity here.
- For now, we will go with the Azure functions to run the spring batch jobs, some batch job runs 4-5 hours daily and for long running jobs we'll explore Azure Containers.  Do you've sample apps around this?
We're hoping to see soon Azure Spring Cloud to run batch jobs as serverless.

Many thanks in advance for great help!

**Comment by jdubois** [comment]
If you store your job metadata in a PostgreSQL database, which is a totally normal and usual configuration, you should automatically have a transaction lock that will prevent running the same job twice concurrently.
Have a look at https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#txConfigForJobRepository - and that’s the default behavior, so it’s important to check that it works, but it’s not surprising if it works 😀
I don’t have anything specific for running Spring Batch on ACI: those are just normal Docker instances, so there’s nothing special to do. I believe your cost will be lower if you have long-running jobs, but it depends on so many parameters that you should do a specific test (my methodology isn’t to do the calculation: I would run them both, and then see the final price at the end of the month!)

**Comment by javaHelper** [comment]
Hey, I am looking to implement the Azure Kafka into my project. Some cases we will build the Producer and Consumers to talk to different microservices - event driven way and other way where we're looking to push & read messages through Spring Batch.

I was going through the link - https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-producer-consumer-api and found no documentation says we can leverage the Spring Cloud stream for the Consumer & producer solution. Is this true? However I see traditional way kafka-client through which we can read & push messages.

Can you guid me if KafkaItemReader and KafkaItemWriter API provided by Spring Batch with the Azure Kafka works well?

https://stackoverflow.com/questions/71169139/how-to-use-kafka-with-the-azure-and-leverage-spring-cloud-stream-or-spring-batch

Thanks

**Comment by jdubois** [comment]
Hi @javaHelper how do you want to create your Kafka cluster? You could create one through the marketplace, using a Docker image, or indeed use one inside HDInsight. You won't get the same versions and features, so maybe that's what can cause you issues. Otherwise, as soon as you have your Kafka cluster, you should be able to use the Spring Cloud stream APIs - I haven't used those for a while, so my knowledge might be a bit outdated, but last time I tried they were a bit simplistic for me, and I preferred to use directly the Kafka Java client.
