### ISSUE TITLE
When I deployed spring-cloud-microservice to Azure Spring Cloud ,but failed

### ISSUE THREAD

**Issue by teo-ma** [microsoft/azure-spring-cloud-training#149]
When I deployed spring-cloud-microservice to Azure Spring Cloud ,but failed.Below are details,

The spring-cloud-microservice app works fine on my local environment,but it failed when deploying to Azure Spring Cloud.

@teo-ma ➜ /workspaces/springcloud-pcsm-training-2022/spring-cloud-microservice (master ✗) $ az spring-cloud app deploy -n spring-cloud-microservice --jar-path target/demo-0.0.1-SNAPSHOT.jar
Option '--jar-path' has been deprecated and will be removed in a future release. Use '--artifact-path' instead.
This command usually takes minutes to run. Add '--verbose' parameter if needed.
file_type is Jar
[1/3] Requesting for upload URL
[2/3] Uploading package to blob
[3/3] Updating deployment in app 'spring-cloud-microservice' (this operation can take a while to complete)
**112404: Failed to wait for deployment instances to be ready. Please check the application log (see https://aka.ms/azure-spring-cloud-doc-log ), and try again later.**

I tried many **bootVersion:2.3.8 ,2.5.7, 2.6.1,2.6.2 with Java11**,however all of them faied.

Any suggestions would be so much appreciated.

Regards,
Teo

**Comment by jdubois** [comment]
Can you first follow the tutorial versions and instructions:

- Spring Boot 2.6.1
- Deployment command using "artefact-path" and not the deprecated "jar-path"

Then can you tell exactly on which step this is failing? This is a pretty long workshop.

**Comment by teo-ma** [comment]
I resolved my issue，I input the wrong confg server issue.Azure Spring Cloud does not display the result,even configured successfully.So I can not check if I input correctly or not.Thanks.
