### ISSUE TITLE
Issue in curl commands while downloading files from spring Instalizer

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/azure-spring-cloud-training#157]
In [Exercise-2>task-1>step-1](https://github.com/microsoft/azure-spring-cloud-training/tree/master/02-build-a-simple-spring-boot-microservice#create-a-simple-spring-boot-microservice), after running the provided curl command `curl https://start.spring.io/starter.tgz -d dependencies=web -d baseDir=simple-microservice -d bootVersion=2.7.0 -d javaVersion=17 | tar -xzvf -`, by default it is downloading the files of Gradle project instead of the files of Maven project from Spring Initializr web page.

![image](https://user-images.githubusercontent.com/83349577/197997533-ff10dec0-d3c0-4fb3-a57f-0485f7a845cb.png)

Due to the incorrect files being downloaded, while performing [Exercise-2>task-3>step-1](https://github.com/microsoft/azure-spring-cloud-training/tree/master/02-build-a-simple-spring-boot-microservice#test-the-project-locally), produces the error message as **No such directory found**  when the command `./mvnw spring-boot:run &` is being run.

![image](https://user-images.githubusercontent.com/83349577/198000567-cefde6c5-ceea-4116-8443-e18c65f54578.png)

**Comment by jdubois** [comment]
Oh Spring has changed its default build tool from Maven to Gradle, I think you have found a huge issue here, thank you!!!

**Comment by jdubois** [comment]
This has been fixed in https://github.com/microsoft/azure-spring-cloud-training/commit/c93525468ae9f07d2c31d8ae266367bd320257c4 - thanks @Divyasri199 for this important bug report!
