### ISSUE TITLE
Section 7: issue creating binding - invalid resource id

### ISSUE THREAD

**Issue by wonderb0lt** [microsoft/azure-spring-cloud-training#50]
Hey guys,

I'm having an issue with section 7. When I do the following set of commands in the git bash: 

```bash
MYSQL_ARM_RESOURCE_ID=$(echo $MYSQL_INFO | jq -r .id)

az spring-cloud app binding mysql add \
    --app weather-service \
    --name mysql-weather \
    --resource-id "$MYSQL_ARM_RESOURCE_ID" \
    --database-name 'azure-spring-cloud-training' \
    --username "$MYSQL_USERNAME" \
    --key "$MYSQL_PASSWORD"
```

I get an error that looks like this.

`Invalid resource id C:/Program Files/Git/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/my-resource-group/providers/Microsoft.DBforMySQL/servers/sclabm-zzzzzzz`                                                                                                                                                                                         

The problem persists if I enter the variables manually into the command.

I'm a bit stumped if this is an issue with my git bash, the terminal I'm using (happens in both ConEmu and the git bash) or with the az spring-cloud command. I hope you'd have an idea or may have seen the issue before.

**Comment by jdubois** [comment]
Can you have a look at `echo $MYSQL_INFO`? This is how we try to get the resource ID, and I believe it's empty for some reason.

**Comment by wonderb0lt** [comment]
Yup, it looks a bit mangled - I initially ascribed that to me using ConEmu, but this persists in the git bash as well.

```
past@vien0098 MINGW64 ~
$ echo $MYSQL_INFO
 "id": "/subscriptions/xxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx/resourceGroups/my- }version": "5.7"e": "Ready",L/servers",",led",/servers/sclabm-zzzzzzzzzz",
```

Running the `az` command directly however seems to produce well-formed JSON, and copying the resource id from the output of it still has the same result as described above

**Comment by jdubois** [comment]
So, even if you copy paste the resource id in the `az spring-cloud app binding mysql` it doesn't work?

**Comment by wonderb0lt** [comment]
Nope. The invocation looked like this:

```bash
az spring-cloud app binding mysql add --app weather-service --name mysql-weather --resource-id "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/my-resource-group/providers/Microsoft.DBforMySQL/servers/sclabm-yyyyyyyyyyyy" --database-name 'azure-spring-cloud-training' --username 'sqlAdmin@sclabm-yyyyyyyyyy' --key 'very secret password'
```
I have since worked around this by just manually creating the MySQL binding in the portal, so there's no hurry.

**Comment by jdubois** [comment]
So you would have 2 problems:
- The $MYSQL_INFO is broken -> I believe this was added by @yevster so I will assign this to him
- Even with the correct resource ID, the resource is still not created... And do you have the same error message in that case?

**Comment by wonderb0lt** [comment]
Yup, that seems to be the case, and yes, the error message is the same.

**Comment by wonderb0lt** [comment]
Hey guys, this happened again today during the actual Discover Workshop 😬  I haven't inlined the commands this time around (since I was busy showing off Azure Spring Cloud!), but the error was the same. This time I also followed the tutorial to the letter, in one go. 

To help you guys reproduce this, here's a bit more info about my envrionment:

OS: Windows 10, build 17134
Azure CLI: 
```
$ az --version
azure-cli                          2.9.1

command-modules-nspkg              2.0.3
core                               2.9.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
spring-cloud                       0.3.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\past\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

Command Line Environment: git bash (git version 2.27.0.windows.1) in a ConEmu (version 200713) prompt. Full bash info:

```
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jdubois** [comment]
Thanks a lot @wonderb0lt - I'm going to ask @selvasingh if we can have help from his team on this, as I didn't work on the ARM templates part

**Comment by yevster** [comment]
Yes, these issues are specific to Git Bash, and its console emulation. One workaround on Windows that will get you unblocked is to use Windows Subsystem for Linux in place of Git Bash. Alternatively, you could use Azure CloudShell for this section. We are looking at ways to make this section workable on Windows.

**Comment by wonderb0lt** [comment]
Thank you @yevster for the pointers for the workaround as I'm holding the workshop again in September! :)

**Comment by jdubois** [comment]
Thank you @wonderb0lt ! If you need help or if you want me to amplify your training, just ping me.

**Comment by yevster** [comment]
This is now resolved in this section, as we've replaced the CLI comand with the portal. There's still an issue in section 11 that we'll track in #98.
