### ISSUE TITLE
Application Insight is now already created by the "az spring-cloud create" command

### ISSUE THREAD

**Issue by wonderb0lt** [microsoft/azure-spring-cloud-training#52]
During my Discover Workshop today I've found that the Azure CLI already creates an Application Insight and hooks it up in regards to logging and distributed tracing, rendering both the resources in the ARM template as well as setting up distributed tracing superfluous. The CLI even says so;:

```
Application Insights "xxxx-xxx-xxxxxxx" was created for this Azure Spring Cloud. You can visit https://portal.azure.com/#resource/subscriptions/xxxxxx-xxx-xxx-xxxxxx/resourceGroups/xxxx-xxx-xxxxxxx/providers/microsoft.insights/components/xxxx-xxx-xxxxxxx/overview to view your Application Insights component
```

If you'd like, I'd love to set up a PR some time next week to edit both the template as well as the instructions

**Comment by jdubois** [comment]
Thank you @wonderb0lt ! Any help on the ARM templates is greatly appreciated, please set up that PR if you can.
