### ISSUE TITLE
Review git bash usage - $RESOURCE_ID vs ${RESOURCE_ID}

### ISSUE THREAD

**Issue by selvasingh** [microsoft/azure-spring-cloud-training#98]
![image](https://user-images.githubusercontent.com/3642444/106368875-f9ae5100-6301-11eb-9a2a-5a015795bbe5.png)

**Comment by mnriem** [comment]
From Git for Windows release notes

If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "/usr/bin/bash.exe" to "C:\Program Files\Git\usr\bin\bash.exe". When that is not desired -- e.g. "--upload-pack=/opt/git/bin/git-upload-pack" or "-L/regex/" -- you need to set the environment variable MSYS_NO_PATHCONV temporarily, like so:

MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc

Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "//usr/bin/bash.exe".

**Comment by selvasingh** [comment]
This sounds good. Let's go
